#!/usr/bin/env bash
#Bash script that displays the time for 12 c_hours and 59 minutes

c_hours=0

while((c_hours <= 12));
do
    echo $"Hour:" $c_hours
    minutes=1
    while ((minutes <= 59));
    do
	echo $minutes
	((minutes++))
    done
    ((c_hours++))
done
