#!/usr/bin/env bash
#Bash script that displays the time for 12 hours and 59 minutes

clock_hours=0

while((clock_hours <= 12));
do
echo $"clock_hours:" $clock_hours
m_mintues=1
while ((m_mintues <= 59));
do
echo $m_mintues
((m_mintues++))
done
((clock_hours++))
done
