#!/usr/bin/env bash
#Bash script that displays

The content of the current directory
for file in *
do
  if [ -f "$file" ] && [ "${file:0:1}" != "." ]
  then
    name=${file#*-}
    echo "$name"
  fi
done
