#!/usr/bin/env bash
#runs nginx as nginx user

sudo pkill apache2
sleep 1
sudo chmod 664 /etc/nginx/nginx.conf
sed -i "s/80/8080/" /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
